name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Code Verification
      uses: actions/checkout@v4
    - name: Foundry Installation
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    - name: Forge Installation
      run: |
        cd hw
        forge install
      id: test
    
    ## Modify Problem 1-9 Configurations
    - name: Problem 1-1
      id: problem-1-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: setAllowedToken
        command: cd hw && forge test --mt testSetMultipleAllowed
        timeout: 10
        max-score: 5

    - name: Problem 1-2
      id: problem-1-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: getValueInETH
        command: cd hw && forge test --mt testgetValueInETH
        timeout: 10
        max-score: 5

    - name: Problem 1-3
      id: problem-1-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Problem 1-3
        command: cd hw && forge test --mt testViewCollateral
        timeout: 10
        max-score: 5

    - name: Problem 1-4
      id: problem-1-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: getTokenValueFromEth
        command: cd hw && forge test --mt testGetTokenValueFromEth
        timeout: 10
        max-score: 5

    - name: Problem 1-5
      id: problem-1-5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: supply
        command: cd hw && forge test --mt testSupply
        timeout: 10
        max-score: 5

    - name: Problem 1-6
      id: problem-1-6
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: borrow
        command: cd hw && forge test --mt testBorrow
        timeout: 10
        max-score: 10

    - name: Problem 1-7
      id: problem-1-7
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: withdraw
        command: cd hw && forge test --mt testWithdraw
        timeout: 10
        max-score: 10

    - name: Problem 1-8
      id: problem-1-8
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: repay
        command: cd hw && forge test --mt testRepay
        timeout: 10
        max-score: 10

    - name: Problem 1-9
      id: problem-1-9
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: liquidate
        command: cd hw && forge test --mt testLiquidate
        timeout: 10
        max-score: 15

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PROBLEM-1-1_RESULTS: "${{steps.problem-1-1.outputs.result}}"
        PROBLEM-1-2_RESULTS: "${{steps.problem-1-2.outputs.result}}"
        PROBLEM-1-3_RESULTS: "${{steps.problem-1-3.outputs.result}}"
        PROBLEM-1-4_RESULTS: "${{steps.problem-1-4.outputs.result}}"
        PROBLEM-1-5_RESULTS: "${{steps.problem-1-5.outputs.result}}"
        PROBLEM-1-6_RESULTS: "${{steps.problem-1-6.outputs.result}}"
        PROBLEM-1-7_RESULTS: "${{steps.problem-1-7.outputs.result}}"
        PROBLEM-1-8_RESULTS: "${{steps.problem-1-8.outputs.result}}"
        PROBLEM-1-9_RESULTS: "${{steps.problem-1-9.outputs.result}}"
      with:
        runners: problem-1-1, problem-1-2, problem-1-3, problem-1-4, problem-1-5, problem-1-6, problem-1-7, problem-1-8, problem-1-9

